env:
  es6: true
  node: true
extends:
  - airbnb-base
  - airbnb-typescript/base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
settings:
  import/resolver: webpack
rules:
  import/no-unresolved: off
