export interface SecretsValues {
  COGNITO_USER_POOL: string
  ENCRYPT_KEY: string
  ENCRYPT_SALT_KEY: string
  PUPPETEER_API_URL: string
  PUPPETEER_API_ACCESS_KEY: string
  PUPPETEER_API_SECRET_KEY: string
  SLACK_TOKEN: string
  SLACK_CLIENT_ID: string
  SLACK_CLIENT_SECRET: string
  SLACK_REDIRECT_URL: string
  SLACK_VERIFICATION_TOKEN: string
  SNS_SLACK_MESSAGE_TOPIC: string
};
